const english = {
  HEADER_TITLE: 'Aran: Plan Manager',
  SETTINGS: 'Settings',
  DAILY_PLAN: 'Daily Plan',
  WEEKLY_PLAN: 'Weekly Plan',
  MONTHLY_PLAN: 'Monthly Plan',
  SETTINGS_LANGUAGE: 'Languages',
  SETTINGS_THEME: 'Theme',
  SETTINGS_BACKUP_RESTORE: 'Backup & Restore',
  SETTINGS_ABOUT: 'About Me',
  ADD_PLAN_MODAL_TITLE: 'Add Plan',
  PLAN_TITLE: 'Plan Title',
  PLAN_TYPES: 'Plan Types',
  PLAN_TYPES_DAILY: 'DAILY',
  PLAN_TYPES_WEEKLY: 'WEEKLY',
  PLAN_TYPES_MONTHLY: 'MONTHLY',
  PLAN_TYPES_EXPLANATION: '* Reset at 00:00 on day, reset the week on Monday, reset the month on first day',
  PLAN_ACHIEVEMENT_TYPES: 'Achievement types',
  PLAN_ACHIEVEMENT_TYPES_COUNT: 'COUNT',
  PLAN_ACHIEVEMENT_TYPES_TIME: 'TIME',
  PLAN_ACHIEVEMENT_TYPES_TIME_SELECTION_BUTTON: 'Set Time',
  PLAN_ACHIEVEMENT_TYPES_ONCE: 'ONCE',
  PLAN_ACHIEVEMENT_TYPES_EXPLANATION: '* To achieve\nCOUNT: you have to do [COUNT] times.\nTIME: you have to do for [TIME].\nONCE: you have to do just once.',
  ADD_PLAN_EXPLANATION: `* You can't edit the plan after adding for avoiding overlap history. but you can delete that. please, check this clearly.`,
  ADD_PLAN_BUTTON: 'Add Plan',
  OK: 'OK',
  CANCEL: 'Cancel',
  HOURS_TEXT: 'Hours',
  MINUTES_TEXT: 'Minutes',
  CURRENT_PROGRESS_TEXT: 'Current Progress',
  GOAL_TEXT: 'Goal',
  APPLY_PROGRESS_TEXT: 'Apply Progress',
  PLAN_HISTORY_TEXT: 'Plan History',
  VIEW_PLAN_HISTORY_TEXT: 'View History',
  END_PLAN_TEXT: 'End Plan',
  PLAN_START_DATE_TEXT: 'Starting Date',
  PLAN_END_DATE_TEXT: 'Ending Date',
  COUNT_SUFFIX: 'times',
  HOW_TO_APPLY_PROGRESS: 'Set values of input boxes then press the apply button to append them to your progress. If your plan type is once, just press the apply button.',
  END_PLAN_TEXT: 'End Plan',
  COMPLETE_PLAN_TEXT: 'Complete Plan',
  END_TEXT: 'END',
  COMPLETE_TEXT: 'COMPLETE',
  KOREAN_TEXT: 'Korean',
  ENGLISH_TEXT: 'English',
  BLACK_THEME: 'Black',
  BLUE_THEME: 'Blue',
  DEVELOPER_INFO_TITLE: 'About Me',
  DEVELOPER_INFO_BODY: 'I wanted an app that can help me for achieving my goals. so I made an idea up then made this. I hope that the app could help you.',
};

export default english;