const english = {
  HEADER_TITLE: 'Aran: Plan Manager',
  SETTINGS: 'Settings',
  DAILY_PLAN: 'Daily Plan',
  WEEKLY_PLAN: 'Weekly Plan',
  MONTHLY_PLAN: 'Monthly Plan',
  SETTINGS_LANGUAGE: 'Languages',
  SETTINGS_THEME: 'Theme',
  SETTINGS_BACKUP_RESTORE: 'Backup & Restore',
  SETTINGS_ABOUT: 'About Me',
  ADD_PLAN_MODAL_TITLE: 'Add Plan',
  PLAN_TITLE: 'Plan Title',
  PLAN_TYPES: 'Plan Types',
  PLAN_TYPES_DAILY: 'DAILY',
  PLAN_TYPES_WEEKLY: 'WEEKLY',
  PLAN_TYPES_MONTHLY: 'MONTHLY',
  PLAN_TYPES_EXPLANATION: '* Reset at 00:00 on day, reset the week on Monday, reset the month on first day',
  PLAN_ACHIEVEMENT_TYPES: 'Achievement types',
  PLAN_ACHIEVEMENT_TYPES_COUNT: 'COUNT',
  PLAN_ACHIEVEMENT_TYPES_TIME: 'TIME',
  PLAN_ACHIEVEMENT_TYPES_TIME_SELECTION_BUTTON: 'Set Time',
  PLAN_ACHIEVEMENT_TYPES_ONCE: 'ONCE',
  PLAN_ACHIEVEMENT_TYPES_EXPLANATION: '* To achieve\nCOUNT: you have to do [COUNT] times.\nTIME: you have to do for [TIME].\nONCE: you have to do just once.',
  ADD_PLAN_EXPLANATION: `* You can't edit the plan after adding for avoiding overlap history. but you can delete that. please, check this clearly.`,
  ADD_PLAN_BUTTON: 'Add Plan',
  OK: 'OK',
  CANCEL: 'Cancel',
  HOURS: 'Hours',
  MINUTES: 'Minutes',
  TOTAL_PROGRESS: 'Total Progress',
  CURRENT_PROGRESS: 'Current Progress',
  GOAL: 'Goal',
  APPLY_PROGRESS: 'Apply Progress',
  VIEW_PLAN_HISTORY: 'View History',
  END_PLAN: 'End Plan',
  PLAN_START_DATE: 'Starting Date',
  PLAN_END_DATE: 'Ending Date',
  COUNT_SUFFIX: 'times',
  HOW_TO_APPLY_PROGRESS: 'Set values of input boxes then press the apply button to append them to your progress. If your plan type is once, just press the apply button.',
  KOREAN: 'Korean',
  ENGLISH: 'English',
  BLACK_THEME: 'Black',
  BLUE_THEME: 'Blue',
  DEVELOPER_INFO_TITLE: 'About Me',
  DEVELOPER_INFO_BODY: 'I wanted an app that can help me for achieving my goals. so I made an idea up then made this. I hope that the app could help you.',
  ALERT_TITLE: 'Alert Window',
  ALERT_INVAILD_TITLE: 'Please, check the title again.',
  ALERT_INVAILD_GOAL: 'Please, check the goal again.',
  ALERT_SUCCESS_TO_ADD_PLAN: 'It\'s succeed to add it into planlist.',
  ALERT_COMPLETE_PLAN_QUESTION: 'If you click OK button, the progress been completed automatically.',
  ALERT_COMPLETE_PLAN_OK: 'It has been completed.',
  ALERT_END_PLAN_QUESTION: 'If you click OK button, this plan will be closed. after closing, you can\'t restore it.',
  ALERT_END_PLAN_OK: 'This plan has been closed.',
  CURRENT_PLANS: 'Current Plans',
  ENDED_PLANS: 'Ended Plans',
  ACTIVITIES: 'Acvities',
  PLAN_NOT_DONE: 'Plan Not done',
  PLAN_DONE: 'Plan Acheieve',
  PLAN_PROGRESSING: 'Plan Not Complete',
  PLAN_OVER_DONE: 'Plan Over Acheieve',
  DATE: 'date',
  DELETE_PLAN: 'Delete Plan',
  ALERT_DELETE_PLAN_TITLE: 'Delete Plan',
  ALERT_DELETE_PLAN_QUESTION: 'Are you sure to delete the plan? after deleting, you can\'t restore it.',
  ALERT_DELETE_HISTORY_TITLE: 'Delete History',
  ALERT_DELETE_HISTORY_QUESTION: 'Are you sure to delete the history?',
  VIEW_MORE: 'View More',
  BACKUP: 'Backup',
  RESTORE: 'Restore',
  EXPORT_DATA: 'Export Data',
  RESTORE_DATA: 'Restore Data',
  DATA: 'data',
  DOES_NOT_SUPPORT: 'This feature doesn\'t support on your device.',
  BACKUP_TITLE: 'Backup - Aran: Plan Manager',
  BACKUP_EXPLANATION: 'Press the button, we gives you the restore data. you have to keep the data for restoring later.',
  RESTORE_EXPLANATION: 'Put your data into the input box and then press the restore button.',
  ALERT_RESTORE_TITLE: 'Data Store',
  ALERT_RESTORE_QUESTION: 'Are you sure to restore the data? all of your current plans will be deleted after.',
  ALERT_RESTORE_FAIL: 'Failed to restore the data. Sorry. please, check your data again.',
  ALERT_RESTORE_SUCCESS: 'It\'s been succeed to restore the data.',
  ALERT_CHECK_INPUT_VALUE: 'Please, ensure your input values.',
};

export default english;