const korean = {
  HEADER_TITLE: '아란: 목표 관리',
  SETTINGS: '설정',
  DAILY_PLAN: '일간 목표',
  WEEKLY_PLAN: '주간 목표',
  MONTHLY_PLAN: '월간 목표',
  SETTINGS_LANGUAGE: '언어 설정',
  SETTINGS_THEME: '테마 설정',
  SETTINGS_BACKUP_RESTORE: '데이터 불러오기/저장하기',
  SETTINGS_ABOUT: '개발자 소개',
  ADD_PLAN_MODAL_TITLE: '목표 추가',
  PLAN_TITLE: '목표',
  PLAN_TYPES: '목표 종류',
  PLAN_TYPES_DAILY: '일간',
  PLAN_TYPES_WEEKLY: '주간',
  PLAN_TYPES_MONTHLY: '월간',
  PLAN_TYPES_EXPLANATION: '* 00시 초기화, 주간은 월요일 초기화, 월간은 1일 날 초기화.',
  PLAN_ACHIEVEMENT_TYPES: '목표 달성 타입',
  PLAN_ACHIEVEMENT_TYPES_COUNT: '횟수',
  PLAN_ACHIEVEMENT_TYPES_TIME: '시간',
  PLAN_ACHIEVEMENT_TYPES_TIME_SELECTION_BUTTON: '시간 변경',
  PLAN_ACHIEVEMENT_TYPES_ONCE: '한번',
  PLAN_ACHIEVEMENT_TYPES_EXPLANATION: '* 목표 달성을 위해\n횟수: 횟수 만큼 해야합니다.\n시간: 시간 만큼 해야합니다.\n한번: 한번만 하면 됩니다.',
  ADD_PLAN_EXPLANATION: '* 계획 생성 후 수정이 불가능 하며, 삭제만 가능합니다. 계획 추가 전 정보를 다시 한번 제대로 확인 해주세요.',
  ADD_PLAN_BUTTON: '계획 추가',
  OK: '확인',
  CANCEL: '취소',
  HOURS_TEXT: '시간',
  MINUTES_TEXT: '분',
  CURRENT_PROGRESS_TEXT: '현재 진행률',
  GOAL_TEXT: '목표',
  APPLY_PROGRESS_TEXT: '진행 적용',
  PLAN_HISTORY_TEXT: '목표 기록',
  VIEW_PLAN_HISTORY_TEXT: '목표 기록 보기',
  END_PLAN_TEXT: '목표 종료',
  PLAN_START_DATE_TEXT: '목표 시작 날짜',
  PLAN_END_DATE_TEXT: '목표 종료 날짜',
  COUNT_SUFFIX: '회',
  HOW_TO_APPLY_PROGRESS: '텍스트의 값을 변경 후에 진행 적용을 누르면 현 진행 사항에 더해지게 됩니다. 한번 타입 목표의 경우에는 진행 적용 버튼만 누르시면 됩니다.',
  END_PLAN_TEXT: '목표 종료',
  COMPLETE_PLAN_TEXT: '목표 완료',
  END_TEXT: '종료',
  COMPLETE_TEXT: '완료',
  KOREAN_TEXT: '한국어',
  ENGLISH_TEXT: '영어',
  BLACK_THEME: '블랙 테마',
  BLUE_THEME: '블루 테마',
  DEVELOPER_INFO_TITLE: '개발자 소개',
  DEVELOPER_INFO_BODY: '일간/주간/월간 목표를 매일 확인 할 수 있고, 목표를 달성했을 때 마다 성취감이 들 수 있게 도와주는 보조 앱이 없을까? 라는 생각이 들어 제작하게 되었습니다.\n앱이 여러분의 목표 달성에 도움이 되길 바랍니다.',
  ALERT_TITLE: '알림창',
  ALERT_INVAILD_TITLE: '제목을 다시 확인해주세요.',
  ALERT_INVAILD_GOAL: '목표 설정값을 다시 확인해주세요.',
  ALERT_SUCCESS_TO_ADD_PLAN: '목표를 추가 했습니다.',
  ALERT_COMPLETE_PLAN_QUESTION: '확인 버튼을 누르면 목표 최대치까지 진행됩니다.',
  ALERT_COMPLETE_PLAN_OK: '목표가 달성되었습니다.',
  ALERT_END_PLAN_QUESTION: '확인 버튼을 누르면 목표를 종료합니다. 다시 복구할 수 없으니 신중히 선택바랍니다.',
  ALERT_END_PLAN_OK: '목표를 종료하였습니다.',
};

export default korean;