const blackTheme = {
  main: '#f5f6fa',
  background: '#2d3436',
  inactive: '#a4b8be',
  activeBackground: '#d8d8e0',
  tabBackground: '#ffff8f',
  groupHeader: '#40739e',
  divider: '#7f8fa6',
  listItemBackground: '#192a56',
  listItemFontColor: '#f5f6fa',
  listItemProgressFontColor: '#f1f8f6',
  doneBackground: '#1dd1a1',
  overDoneBackground: '#10ac84',
  progressingBackground: '#ff9f43',
  notDoneBackground: '#d63031',
  headerBackground: '#636e72',
  headerTitle: '#dfe6e9',
  historyLeftSideFont: '#ffffff',
  historyLeftSideBackground: '#1e90ff',
  historyRightSideFont: '#ffffff',
  historyRightSideBackground: '#5352ed',
  cancel: '#e84118',
  explanation: '#dcdde1',
};

export default blackTheme;