const blueTheme = {
  main: '#3867d6',
  background: '#ffffff',
  inactive: '#a4b0be',
  activeBackground: '#d1d8e0',
  tabBackground: '#ffffff',
  groupHeader: '#70a1ff',
  divider: '#70a1ff',
  listItemBackground: '#70a1ff',
  listItemFontColor: '#ffffff',
  listItemProgressFontColor: '#f1f2f6',
  doneBackground: '#7bed9f',
  overDoneBackground: '#2ed573',
  progressingBackground: '#eccc68',
  notDoneBackground: '#ff4757',
  headerBackground: '#ffffff',
  headerTitle: '#3867d6',
  historyLeftSideFont: '#ffffff',
  historyLeftSideBackground: '#1e90ff',
  historyRightSideFont: '#ffffff',
  historyRightSideBackground: '#5352ed',
  cancel: '#d63031',
  explanation: '#808e9b',
};

export default blueTheme;